### PR TITLE
Fix issue 55

### LINKED ISSUE #55: Add relationship between users and events table

### LINKED ISSUE #57: [#35] can't create an event

### PR DESCRIPTION
**Pull request by shin5446**
## content
- add relationship between users and events table
- connect to back end for create event function
- add error messages

## image
スクリーンショット 2023-06-13 午後4 07 40

## issue
fixed #55 fixed #57

### CODE REVIEW

File: src/resources/js/Pages/Event/EventForm.jsx [hunk 1]
```diff
@@ -3,14 +3,17 @@ import TimeForm from "./TimeForm";
...
-
-    const handleLimitChange = (e) => {
-        setLimit(e.target.value);
-    };
+    const [name, setName] = React.useState("");
+    const [description, setDescription] = React.useState("");
+    const [address, setAddress] = React.useState("");
+    const [startTime, setStartTime] = React.useState("");
+    const [endTime, setEndTime] = React.useState("");
+    const { errors, auth } = props
```
Comment (akaka0039) [inline src/resources/js/Pages/Event/EventForm.jsx:15]: is it possible to get an auth data?

File: src/resources/js/Pages/Event/EventForm.jsx [hunk 2]
```diff
@@ -3,14 +3,17 @@ import TimeForm from "./TimeForm";
 import Header from "@/Components/Header";
 import { router } from "@inertiajs/react";
 
-const EventForm = () => {
+const EventForm = (props) => {
```
Comment (akaka0039) [inline src/resources/js/Pages/Event/EventForm.jsx:6]: At this time, should be like this:
```
const EventForm = ({ auth, errors }) => {
```
but it is correct, depend on person
