### PR TITLE
Fix issue 327, 330

### LINKED ISSUE #327: [#332] Add logic for list page for event team

### LINKED ISSUE #330: [#332] Add logic for attaching event team to the event

### PR DESCRIPTION
**Pull request by shin5446**
## Related Issue
fixed #327 
fixed #330

### CODE REVIEW

File: src/app/Models/User.php [hunk 1]
```diff
@@ -74,10 +76,19 @@ public function participantEvents(): BelongsToMany
     }
 
     /**
-     *
+     * Get the social accounts for the user.
```
Comment (akaka0039) [inline src/app/Models/User.php:79]: thank you for this comment. I missed this

File: src/resources/js/Components/Pages/Event/EventForm.jsx [hunk 2]
```diff
@@ -4,11 +4,12 @@ import TimeForm from "./EventFormComponents/TimeForm";
 import Button from "@/Components/Ui/Button";
 import Switch from "@/Components/Pages/Event/EventFormComponents/AddressForm";
 
-const EventForm = ({ errors, auth, tags, event, related_tags }) => {
+const EventForm = ({ errors, auth, tags, event, related_tags, event_teams, event_team_id }) => {
```
Comment (akaka0039) [inline src/resources/js/Components/Pages/Event/EventForm.jsx:7]: Is 'event_team_id' necessary ?
I think 'event_teams' contains it

File: src/resources/js/Components/Ui/FlashMessage.jsx [hunk 3]
```diff
@@ -17,6 +17,9 @@ export default function FlashMessage({ flash }) {
             case /update/.test(type):
             color = 'green';
             break;
+            case /warn/.test(type):
+            color = 'orange';
+            break;
```
Comment (akaka0039) [inline src/resources/js/Components/Ui/FlashMessage.jsx:22]: I love this!

File: src/resources/js/Components/Pages/Event/EventForm.jsx (hunk 2 above)
Comment (akaka0039) [reply src/resources/js/Components/Pages/Event/EventForm.jsx:7]: if you checked [this ticket](https://github.com/users/akaka0039/projects/32/views/1?pane=issue&itemId=36913881) and add it, you don't have to add it. I just wanted to avoid of the error.
sorry for making you confused.

**Review by akaka0039 — APPROVED** [review]
Great Work!!!

File: src/resources/js/Components/Pages/Event/EventForm.jsx (hunk 2 above)
Comment (shin5446) [reply src/resources/js/Components/Pages/Event/EventForm.jsx:7]: No, this event_team_id is needed when updating the event.

Comment (shin5446) [reply src/resources/js/Components/Pages/Event/EventForm.jsx:7]: The event_teams are associated with the user and are used to display select boxes. I will refactor it to make it a little clearer.
