### PR TITLE
FIx logic to create participant

### LINKED ISSUE #104: [#35] A host should attend the event the host created

### PR DESCRIPTION
**Pull request by shin5446**
## Content
- fix logic to attach participants to the event.
- fix the display for attend button
## Related Issue
fixed #104

### CODE REVIEW

File: src/app/Http/Requests/StoreEventRequest.php [hunk 1]
```diff
@@ -26,7 +26,7 @@ public function rules(): array
             'user_id' => ['required', 'integer'],
             'name' => ['required', 'string', 'max:255'],
             'address' => $this->input('is_online') ? ['required', 'url'] : ['required', 'string', 'max:255'],
-            'participant_limit_number' => [ 'required', 'integer'],
+            'participant_limit_number' => [ 'required', 'integer', 'min:2'],
```
Comment (akaka0039) [inline src/app/Http/Requests/StoreEventRequest.php:29]: nice!!!

**Review by akaka0039 — APPROVED** [review]

File: src/app/Models/Event.php [hunk 2]
```diff
@@ -79,6 +79,19 @@ public function isAttended(): bool
...
+     */
+    public function isHosted(): bool
+    {
+        if (!auth()->check() && is_null(auth()->user())) {
+            return false;
+        }
+
+        return $this->user_id === auth()->id();
+    }
+
```
Comment (akaka0039) [inline src/app/Models/Event.php:94]: not use host table?

Comment (shin5446) [reply src/app/Models/Event.php:94]: I'm sorry, I didn't explain! I will use the host table later, but I wrote it this way for convenience.

**Review by akaka0039 — APPROVED** [review]
