### PR TITLE
Fix default user image

### LINKED ISSUE #242: [#198] Allow user profile default images to be managed under the public/images directory.

### PR DESCRIPTION
**Pull request by shin5446**
## Content
As the title says
## Related Issue
fixed #242

### CODE REVIEW

File: src/resources/js/Components/Pages/Top/Top_2.jsx [hunk 1]
```diff
@@ -1,6 +1,6 @@
 import React from "react";
 import Networking from "/public/images/Networking.png";
-import Global from "/public/images/Global.png";
+import Global from "/public/images/default_user.svg";
```
Comment (akaka0039) [inline src/resources/js/Components/Pages/Top/Top_2.jsx:3]: Could you tell me why you changed this one?

Comment (shin5446) [reply src/resources/js/Components/Pages/Top/Top_2.jsx:3]: Oh, this is simply because I forgot to revert back to the original code when I was checking Its appearance.
Thank you for telling me. Good catch!!
