### PR TITLE
Fix issue#212

### LINKED ISSUE #212: [#197] Add method of markdown or other option to edit Description

### PR DESCRIPTION
**Pull request by shin5446**
## Content
 [#197] Add method of markdown or other option to edit Description
### input
スクリーンショット 2023-07-28 午後10 07 10
スクリーンショット 2023-07-28 午後10 07 49

### output
スクリーンショット 2023-07-28 午後10 08 25
スクリーンショット 2023-07-28 午後10 08 45

## Related Issue
fixed #212 

## notes
I installed those packages.
For markdown, I installed this.
https://github.com/remarkjs/react-markdown
For the support table and the checkbox in markdown, I installed this.
https://github.com/remarkjs/remark-gfm
To address the issue with tailwind css, I installed this
https://github.com/tailwindlabs/tailwindcss-typography
issue↓
https://tailwindcss.com/docs/preflight#headings-are-unstyled

### CODE REVIEW

File: src/resources/js/Components/Pages/Main/Card.jsx [hunk 1]
```diff
@@ -22,11 +22,12 @@ const Card = ({ event }) => {
                     style={cardStyle}
                 ></div>
                 <div className="p-4">
-                    <h2 className="text-xl text-gray-700 font-bold mb-2" key={event.event_id}>
+                    <h2 className="text-xl text-gray-700 text-center font-bold mb-2" key={event.event_id}>
                         {event.name}
                     </h2>
-                    <p className="text-gray-600 truncate">
-                        {event.description}
+                    <p className="text-gray-600 text-center truncate" key={event.event_id}>
```
Comment (akaka0039) [inline src/resources/js/Components/Pages/Main/Card.jsx:28]: You don't have to set a key by using an 'event_id' here.
it displays the console error because of duplicate

d the key

**Review by akaka0039 — APPROVED** [review]
Great Job!!!
